using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Stringier {
	public readonly partial struct Glyph {
		//! Please do not use graphemes in this table; use the fully escaped codepoints. The graphemes would be visually identical (that's the point }), and would be remarkably difficult to find and fix errors.

		/// <summary>
		/// Invariant equivalency table.
		/// </summary>
		/// <remarks>
		/// This intends to implement UAX#29 (https://unicode.org/reports/tr29/).
		/// </remarks>
		[SuppressMessage("Major Bug", "S3263:Static fields should appear in the order they must be initialized ", Justification = "It's almost like that's why this is at the bottom...")]
		internal static readonly Table InvariantTable = new Table(
			#region Latin-1 Supplement
			new KeyValuePair<String, Char>("\u00C0", 'À'),
			new KeyValuePair<String, Char>("\u0041\u0300", 'À'),
			new KeyValuePair<String, Char>("\u00C1", 'Á'),
			new KeyValuePair<String, Char>("\u0041\u0301", 'Á'),
			new KeyValuePair<String, Char>("\u00C2", 'Â'),
			new KeyValuePair<String, Char>("\u0041\u0302", 'Â'),
			new KeyValuePair<String, Char>("\u00C3", 'Ã'),
			new KeyValuePair<String, Char>("\u0041\u0303", 'Ã'),
			new KeyValuePair<String, Char>("\u00C4", 'Ä'),
			new KeyValuePair<String, Char>("\u0041\u0308", 'Ä'),
			new KeyValuePair<String, Char>("\u00C5", 'Å'),
			new KeyValuePair<String, Char>("\u0041\u030A", 'Å'),
			new KeyValuePair<String, Char>("\u00C6", 'Æ'),
			new KeyValuePair<String, Char>("\u0041\u0045", 'Æ'),
			new KeyValuePair<String, Char>("\u00C7", 'Ç'),
			new KeyValuePair<String, Char>("\u0043\u0327", 'Ç'),
			new KeyValuePair<String, Char>("\u00C8", 'È'),
			new KeyValuePair<String, Char>("\u0045\u0300", 'È'),
			new KeyValuePair<String, Char>("\u00C9", 'É'),
			new KeyValuePair<String, Char>("\u0045\u0301", 'É'),
			new KeyValuePair<String, Char>("\u00CA", 'Ê'),
			new KeyValuePair<String, Char>("\u0045\u0302", 'Ê'),
			new KeyValuePair<String, Char>("\u00CB", 'Ë'),
			new KeyValuePair<String, Char>("\u0045\u0308", 'Ë'),
			new KeyValuePair<String, Char>("\u00CC", 'Ì'),
			new KeyValuePair<String, Char>("\u0049\u0300", 'Ì'),
			new KeyValuePair<String, Char>("\u00CD", 'Í'),
			new KeyValuePair<String, Char>("\u0049\u0301", 'Í'),
			new KeyValuePair<String, Char>("\u00CE", 'Î'),
			new KeyValuePair<String, Char>("\u0049\u0302", 'Î'),
			new KeyValuePair<String, Char>("\u00CF", 'Ï'),
			new KeyValuePair<String, Char>("\u0049\u0308", 'Ï'),
			new KeyValuePair<String, Char>("\u00D1", 'Ñ'),
			new KeyValuePair<String, Char>("\u004E\u0303", 'Ñ'),
			new KeyValuePair<String, Char>("\u00D2", 'Ò'),
			new KeyValuePair<String, Char>("\u004F\u0300", 'Ò'),
			new KeyValuePair<String, Char>("\u00D3", 'Ó'),
			new KeyValuePair<String, Char>("\u004F\u0301", 'Ó'),
			new KeyValuePair<String, Char>("\u00D4", 'Ô'),
			new KeyValuePair<String, Char>("\u004F\u0302", 'Ô'),
			new KeyValuePair<String, Char>("\u00D5", 'Õ'),
			new KeyValuePair<String, Char>("\u004F\u0303", 'Õ'),
			new KeyValuePair<String, Char>("\u00D6", 'Ö'),
			new KeyValuePair<String, Char>("\u004F\u0308", 'Ö'),
			new KeyValuePair<String, Char>("\u00D9", 'Ù'),
			new KeyValuePair<String, Char>("\u0055\u0300", 'Ù'),
			new KeyValuePair<String, Char>("\u00DA", 'Ú'),
			new KeyValuePair<String, Char>("\u0055\u0301", 'Ú'),
			new KeyValuePair<String, Char>("\u00DB", 'Û'),
			new KeyValuePair<String, Char>("\u0055\u0302", 'Û'),
			new KeyValuePair<String, Char>("\u00DC", 'Ü'),
			new KeyValuePair<String, Char>("\u0055\u0308", 'Ü'),
			new KeyValuePair<String, Char>("\u00DD", 'Ý'),
			new KeyValuePair<String, Char>("\u0059\u0301", 'Ý'),
			new KeyValuePair<String, Char>("\u00E0", 'à'),
			new KeyValuePair<String, Char>("\u0061\u0300", 'à'),
			new KeyValuePair<String, Char>("\u00E1", 'á'),
			new KeyValuePair<String, Char>("\u0061\u0301", 'á'),
			new KeyValuePair<String, Char>("\u00E2", 'â'),
			new KeyValuePair<String, Char>("\u0061\u0302", 'â'),
			new KeyValuePair<String, Char>("\u00E3", 'ã'),
			new KeyValuePair<String, Char>("\u0061\u0303", 'ã'),
			new KeyValuePair<String, Char>("\u00E4", 'ä'),
			new KeyValuePair<String, Char>("\u0061\u0308", 'ä'),
			new KeyValuePair<String, Char>("\u00E5", 'å'),
			new KeyValuePair<String, Char>("\u0061\u030A", 'å'),
			new KeyValuePair<String, Char>("\u00E6", 'æ'),
			new KeyValuePair<String, Char>("\u0061\u0065", 'æ'),
			new KeyValuePair<String, Char>("\u00E7", 'ç'),
			new KeyValuePair<String, Char>("\u0063\u0327", 'ç'),
			new KeyValuePair<String, Char>("\u00E8", 'è'),
			new KeyValuePair<String, Char>("\u0065\u0300", 'è'),
			new KeyValuePair<String, Char>("\u00E9", 'é'),
			new KeyValuePair<String, Char>("\u0065\u0301", 'é'),
			new KeyValuePair<String, Char>("\u00EA", 'ê'),
			new KeyValuePair<String, Char>("\u0065\u0302", 'ê'),
			new KeyValuePair<String, Char>("\u00EB", 'ë'),
			new KeyValuePair<String, Char>("\u0065\u0308", 'ë'),
			new KeyValuePair<String, Char>("\u00EC", 'ì'),
			new KeyValuePair<String, Char>("\u0069\u0300", 'ì'),
			new KeyValuePair<String, Char>("\u00ED", 'í'),
			new KeyValuePair<String, Char>("\u0069\u0301", 'í'),
			new KeyValuePair<String, Char>("\u00EE", 'î'),
			new KeyValuePair<String, Char>("\u0069\u0302", 'î'),
			new KeyValuePair<String, Char>("\u00EF", 'ï'),
			new KeyValuePair<String, Char>("\u0069\u0308", 'ï'),
			new KeyValuePair<String, Char>("\u00F1", 'ñ'),
			new KeyValuePair<String, Char>("\u006E\u0303", 'ñ'),
			new KeyValuePair<String, Char>("\u00F2", 'ò'),
			new KeyValuePair<String, Char>("\u006F\u0300", 'ò'),
			new KeyValuePair<String, Char>("\u00F3", 'ó'),
			new KeyValuePair<String, Char>("\u006F\u0301", 'ó'),
			new KeyValuePair<String, Char>("\u00F4", 'ô'),
			new KeyValuePair<String, Char>("\u006F\u0302", 'ô'),
			new KeyValuePair<String, Char>("\u00F5", 'õ'),
			new KeyValuePair<String, Char>("\u006F\u0303", 'õ'),
			new KeyValuePair<String, Char>("\u00F6", 'ö'),
			new KeyValuePair<String, Char>("\u006F\u0308", 'ö'),
			new KeyValuePair<String, Char>("\u00F9", 'ù'),
			new KeyValuePair<String, Char>("\u0075\u0300", 'ù'),
			new KeyValuePair<String, Char>("\u00FA", 'ú'),
			new KeyValuePair<String, Char>("\u0075\u0301", 'ú'),
			new KeyValuePair<String, Char>("\u00FB", 'û'),
			new KeyValuePair<String, Char>("\u0075\u0302", 'û'),
			new KeyValuePair<String, Char>("\u00FC", 'ü'),
			new KeyValuePair<String, Char>("\u0075\u0308", 'ü'),
			new KeyValuePair<String, Char>("\u00FD", 'ý'),
			new KeyValuePair<String, Char>("\u0079\u0301", 'ý'),
			new KeyValuePair<String, Char>("\u00FE", 'ÿ'),
			new KeyValuePair<String, Char>("\u0079\u0308", 'ÿ')
			#endregion
			);
	}
}
