name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      uses: nikeee/docfx-action@v1.0.0
      with: 
        args: ./Documentation/docfx.json
    - name: Publish
      uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: Rebuilt docs
        commit_user_name: DocFX
