name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Coverlet
      uses: b3b00/coverlet-action@1.0.91
      with:
        output: lcov.info
        outputFormat: lcov
        testProject: 'Tests/Tests.vbproj'
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.COVERALLS }}
        path-to-lcov: ${{ steps.Coverlet.outputs.coverageFile }}
